const canvas=document.getElementById('rain');
const ctx=canvas.getContext('2d');
const SAVE_KEY='rainGardenSave:v1';
const OFFLINE_CAP_SECONDS=8*60*60;
const AUTOSAVE_MS=10000;
const upgradeNames={clouds:'More Clouds',ripples:'Deeper Ripples',mist:'Mist Catcher'};
const milestones=[{name:'Mossy Ground',value:100,message:'Moss spreads through the garden.'},{name:'Flowerbed',value:1000,message:'Moonflowers begin to bloom.'},{name:'Moon Pond',value:10000,message:'The pond starts to glow.'},{name:'Firefly Grove',value:100000,message:'Fireflies arrive.'}];
const ui={hud:document.getElementById('hud'),water:document.getElementById('water'),waterDetail:document.getElementById('waterDetail'),rate:document.getElementById('rate'),rateDetail:document.getElementById('rateDetail'),stage:document.getElementById('stage'),stageDetail:document.getElementById('stageDetail'),nextMilestone:document.getElementById('nextMilestone'),milestoneProgress:document.getElementById('milestoneProgress'),saved:document.getElementById('saved'),toast:document.getElementById('toast'),reset:document.getElementById('reset'),devToggle:document.getElementById('devToggle'),devPanel:document.getElementById('devPanel'),devButtons:[...document.querySelectorAll('[data-dev]')],panelButtons:[...document.querySelectorAll('[data-panel]')],panels:[...document.querySelectorAll('.sheet')],closeButtons:[...document.querySelectorAll('[data-close]')],buttons:[...document.querySelectorAll('.upgrade')],costs:{clouds:document.getElementById('cloudsCost'),ripples:document.getElementById('ripplesCost'),mist:document.getElementById('mistCost')},levels:{clouds:document.getElementById('cloudsLevel'),ripples:document.getElementById('ripplesLevel'),mist:document.getElementById('mistLevel')}};
let width=0,height=0,dpr=Math.min(window.devicePixelRatio||1,2);
let drops=[],ripples=[],mist=[],sparks=[],mossPatches=[],flowers=[],ambientFireflies=[],cloudShapes=[],reeds=[];
let special=null,specialCooldown=16,recentWater=[];
let lastSavedAt=Date.now(),lastAutoSaveAt=Date.now(),toastTimer=null,dropSpawnTimer=0,seenMilestoneLevel=0;
const state={water:0,lifetimeWater:0,upgrades:{clouds:0,ripples:0,mist:0},lastSavedAt:Date.now()};
const random=(min,max)=>Math.random()*(max-min)+min;
const landingY=()=>random(height*.66,height*.98);
const format=n=>n<1000?Math.floor(n).toString():n<1e6?(n/1000).toFixed(1)+'k':n<1e9?(n/1e6).toFixed(1)+'m':(n/1e9).toFixed(1)+'b';
const costs={clouds:()=>Math.floor(12*Math.pow(1.68,state.upgrades.clouds)),ripples:()=>Math.floor(25*Math.pow(1.74,state.upgrades.ripples)),mist:()=>Math.floor(50*Math.pow(1.86,state.upgrades.mist))};
const waterPerDrop=()=>1+state.upgrades.ripples*.65;
const passivePerSecond=()=>state.upgrades.mist*.28;
const dropInterval=()=>Math.max(.42,3*Math.pow(.78,state.upgrades.clouds));
const maxActiveDrops=()=>2+state.upgrades.clouds*2;
const rippleVisualBoost=()=>1+Math.min(.7,state.upgrades.ripples*.08);
const mistVisualBoost=()=>1+Math.min(.9,state.upgrades.mist*.09);
function seededRandom(seed){const x=Math.sin(seed)*10000;return x-Math.floor(x)}
function buildGardenDecorations(){mossPatches=Array.from({length:34},(_,i)=>({x:seededRandom(i*14.7+2)*width,y:height*(.72+seededRandom(i*11.3+5)*.24),radius:18+seededRandom(i*8.1+9)*42,flatness:.22+seededRandom(i*4.8+3)*.18,phase:seededRandom(i*5.2+1)*Math.PI*2}));flowers=Array.from({length:22},(_,i)=>({x:seededRandom(i*19.9+7)*width,y:height*(.68+seededRandom(i*15.1+4)*.25),stem:10+seededRandom(i*3.6+8)*24,size:3.5+seededRandom(i*2.7+6)*4.5,phase:seededRandom(i*6.1+3)*Math.PI*2}));ambientFireflies=Array.from({length:18},(_,i)=>({x:seededRandom(i*13.3+1)*width,y:height*(.44+seededRandom(i*10.1+12)*.42),radius:18+seededRandom(i*3.9+4)*46,speed:.00035+seededRandom(i*7.7+8)*.00045,phase:seededRandom(i*9.4+2)*Math.PI*2,size:1.1+seededRandom(i*5.8+11)*1.9}));cloudShapes=Array.from({length:8},(_,i)=>({x:seededRandom(i*21.1+4)*width,y:height*(.08+seededRandom(i*17.5+2)*.16),radius:70+seededRandom(i*12.8+6)*130,speed:4+seededRandom(i*7.4+5)*8,phase:seededRandom(i*9.8+3)*Math.PI*2}));reeds=Array.from({length:18},(_,i)=>({x:seededRandom(i*22.4+8)*width,y:height*(.78+seededRandom(i*9.7+1)*.18),height:18+seededRandom(i*6.5+3)*42,phase:seededRandom(i*3.5+10)*Math.PI*2}))}
function milestoneLevel(){if(state.lifetimeWater>=100000)return 4;if(state.lifetimeWater>=10000)return 3;if(state.lifetimeWater>=1000)return 2;if(state.lifetimeWater>=100)return 1;return 0}
function nextMilestone(){return milestones.find(m=>state.lifetimeWater<m.value)||null}
function setOpenPanel(panelId){for(const panel of ui.panels){const open=panel.id===panelId&&!panel.classList.contains('open');panel.classList.toggle('open',open);panel.setAttribute('aria-hidden',String(!open))}for(const button of ui.panelButtons){const expanded=document.getElementById(button.dataset.panel).classList.contains('open');button.setAttribute('aria-expanded',String(expanded))}}
function closePanel(panelId){const panel=document.getElementById(panelId);panel.classList.remove('open');panel.setAttribute('aria-hidden','true');const button=ui.panelButtons.find(item=>item.dataset.panel===panelId);if(button)button.setAttribute('aria-expanded','false')}
function showToast(message,duration=4800){ui.toast.textContent=message;ui.toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('visible'),duration)}
function pulseHud(){ui.hud.classList.remove('pulse');void ui.hud.offsetWidth;ui.hud.classList.add('pulse')}
function checkMilestoneUnlocks(){const current=milestoneLevel();if(current<=seenMilestoneLevel)return;for(let level=seenMilestoneLevel+1;level<=current;level++){const milestone=milestones[level-1];if(milestone)showToast(milestone.message)}seenMilestoneLevel=current;pulseHud()}
function addWater(amount,trackRate=true,checkMilestones=true){state.water+=amount;state.lifetimeWater+=amount;if(trackRate)recentWater.push({amount,time:performance.now()});if(checkMilestones)checkMilestoneUnlocks()}
function recentRate(now){recentWater=recentWater.filter(entry=>now-entry.time<5000);return recentWater.reduce((sum,entry)=>sum+entry.amount,0)/5+passivePerSecond()}
function gardenStage(){if(state.lifetimeWater>=100000)return'Firefly Grove';if(state.lifetimeWater>=10000)return'Moon Pond';if(state.lifetimeWater>=1000)return'Flowerbed';if(state.lifetimeWater>=100)return'Mossy Ground';return'Seedbed'}
function updateSavedLabel(){const seconds=Math.max(0,Math.floor((Date.now()-lastSavedAt)/1000));ui.saved.textContent=seconds<5?'now':`${seconds}s ago`}
function updateUI(now=performance.now()){const water=format(state.water),rate=format(recentRate(now))+'/s',stage=gardenStage(),next=nextMilestone();ui.water.textContent=water;ui.waterDetail.textContent=water;ui.rate.textContent=rate;ui.rateDetail.textContent=rate;ui.stage.textContent=stage;ui.stageDetail.textContent=stage;ui.nextMilestone.textContent=next?`${next.name} at ${format(next.value)}`:'Complete';ui.milestoneProgress.textContent=next?`${format(state.lifetimeWater)} / ${format(next.value)}`:`${format(state.lifetimeWater)} lifetime`;updateSavedLabel();for(const button of ui.buttons){const key=button.dataset.upgrade,cost=costs[key]();ui.costs[key].textContent=format(cost);ui.levels[key].textContent=`Level ${state.upgrades[key]}`;button.disabled=state.water<cost}}
function saveGame(){state.lastSavedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(state));lastSavedAt=state.lastSavedAt}
function loadGame(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return;const saved=JSON.parse(raw);if(!saved||typeof saved!=='object')return;state.water=Number.isFinite(saved.water)?Math.max(0,saved.water):0;state.lifetimeWater=Number.isFinite(saved.lifetimeWater)?Math.max(state.water,saved.lifetimeWater):state.water;state.upgrades={clouds:Math.max(0,Number(saved.upgrades?.clouds)||0),ripples:Math.max(0,Number(saved.upgrades?.ripples)||0),mist:Math.max(0,Number(saved.upgrades?.mist)||0)};const savedAt=Number(saved.lastSavedAt)||Date.now();const elapsedSeconds=Math.min(OFFLINE_CAP_SECONDS,Math.max(0,(Date.now()-savedAt)/1000));const offlineWater=passivePerSecond()*elapsedSeconds;if(offlineWater>=1){addWater(offlineWater,false,false);showToast(`While you were away, the garden gathered ${format(offlineWater)} water.`)}lastSavedAt=savedAt}catch(error){console.warn('Could not load save data:',error);showToast('Save data could not be loaded, so a fresh garden was started.')}}
function maybeAutoSave(){if(Date.now()-lastAutoSaveAt<AUTOSAVE_MS)return;saveGame();lastAutoSaveAt=Date.now()}
function buyUpgrade(key){const cost=costs[key]();if(state.water<cost)return;state.water-=cost;state.upgrades[key]+=1;trimActiveDrops();saveGame();updateUI();pulseHud();showToast(`${upgradeNames[key]} grew stronger.`)}
function resetGame(skipConfirm=false){if(!skipConfirm&&!confirm('Reset your rain garden progress?'))return;state.water=0;state.lifetimeWater=0;state.upgrades={clouds:0,ripples:0,mist:0};seenMilestoneLevel=0;recentWater=[];drops=[];dropSpawnTimer=0;localStorage.removeItem(SAVE_KEY);saveGame();showToast('The garden has been reset.');updateUI()}
function trimActiveDrops(){const max=maxActiveDrops();if(drops.length>max)drops.length=max}
function resize(){dpr=Math.min(window.devicePixelRatio||1,2);width=window.innerWidth;height=window.innerHeight;canvas.width=Math.floor(width*dpr);canvas.height=Math.floor(height*dpr);canvas.style.width=width+'px';canvas.style.height=height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);mist=Array.from({length:Math.max(10,Math.floor(width/90))},createMist);buildGardenDecorations();drops=[];dropSpawnTimer=0}
function createDrop(){const depth=random(.35,1),impactY=landingY();return{x:random(-width*.1,width*1.1),y:random(-height*.18,-28),length:random(12,34)*depth,speed:random(210,460)*depth,drift:random(-22,-7)*depth,alpha:random(.14,.36)*depth,lineWidth:random(.6,1.2)*depth,depth,impactY}}
function spawnDrops(delta){dropSpawnTimer+=delta;const interval=dropInterval(),cap=maxActiveDrops();while(dropSpawnTimer>=interval&&drops.length<cap){drops.push(createDrop());dropSpawnTimer-=interval}if(drops.length>=cap)dropSpawnTimer=Math.min(dropSpawnTimer,interval)}
function createMist(){return{x:random(0,width),y:random(height*.58,height*.98),radius:random(90,230),speed:random(3,10),alpha:random(.01,.027)}}
function createRipple(x,y,strength=1,warm=false){const boost=rippleVisualBoost();ripples.push({x,y,radius:1,alpha:(warm?.3:.18)*boost,growth:random(18,42)*strength*boost,stretch:random(1.45,2.15)+Math.min(.35,state.upgrades.ripples*.025),warm,double:state.upgrades.ripples>=2&&!warm})}
function maybeStartSpecial(delta){if(special)return;specialCooldown-=delta;if(specialCooldown>0)return;if(Math.random()<delta/190){forceGoldenDrop();specialCooldown=random(120,240)}}
function forceGoldenDrop(){special={x:random(width*.15,width*.85),y:-80,impactY:landingY(),speed:random(160,230),drift:random(-6,6),length:42,phase:'falling',age:0}}
function drawBackground(time){const pulse=.04+Math.sin(time*.00018)*.015;const gradient=ctx.createRadialGradient(width*.5,height*.18,0,width*.5,height*.22,Math.max(width,height));gradient.addColorStop(0,`rgba(49, 74, 104, ${.88+pulse})`);gradient.addColorStop(.42,'rgba(17, 25, 35, .96)');gradient.addColorStop(1,'rgba(5, 8, 12, 1)');ctx.fillStyle=gradient;ctx.fillRect(0,0,width,height)}
function drawClouds(time){if(state.upgrades.clouds<=0)return;const count=Math.min(cloudShapes.length,1+Math.floor(state.upgrades.clouds/2));const alpha=Math.min(.12,.025+state.upgrades.clouds*.008);ctx.save();for(let i=0;i<count;i++){const cloud=cloudShapes[i];const x=(cloud.x+time*.001*cloud.speed)%(width+cloud.radius*2)-cloud.radius;const y=cloud.y+Math.sin(time*.0004+cloud.phase)*7;const grad=ctx.createRadialGradient(x,y,0,x,y,cloud.radius);grad.addColorStop(0,`rgba(190, 215, 235, ${alpha})`);grad.addColorStop(1,'rgba(190, 215, 235, 0)');ctx.fillStyle=grad;ctx.beginPath();ctx.ellipse(x,y,cloud.radius,cloud.radius*.28,0,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawGarden(time){const level=milestoneLevel();ctx.save();if(state.upgrades.mist>0)drawMistCatchers(time);if(level>=1){for(const moss of mossPatches){const pulse=.85+Math.sin(time*.001+moss.phase)*.15;ctx.fillStyle=`rgba(80, 132, 100, ${.075*pulse})`;ctx.beginPath();ctx.ellipse(moss.x,moss.y,moss.radius,moss.radius*moss.flatness,0,0,Math.PI*2);ctx.fill()}}if(level>=3){const pond=ctx.createRadialGradient(width*.5,height*.9,0,width*.5,height*.9,Math.max(width,height)*.42);const shimmer=.1+Math.sin(time*.0007)*.035;pond.addColorStop(0,`rgba(118, 178, 202, ${shimmer})`);pond.addColorStop(.55,'rgba(80, 130, 160, 0.045)');pond.addColorStop(1,'rgba(80, 130, 160, 0)');ctx.fillStyle=pond;ctx.beginPath();ctx.ellipse(width*.5,height*.9,width*.46,height*.18,0,0,Math.PI*2);ctx.fill()}if(level>=2){for(const flower of flowers){const sway=Math.sin(time*.0012+flower.phase)*2.2;ctx.strokeStyle='rgba(112, 168, 126, 0.28)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(flower.x,flower.y);ctx.quadraticCurveTo(flower.x+sway,flower.y-flower.stem*.55,flower.x+sway*1.4,flower.y-flower.stem);ctx.stroke();const bloomX=flower.x+sway*1.4,bloomY=flower.y-flower.stem;ctx.fillStyle='rgba(218, 230, 255, 0.2)';ctx.beginPath();ctx.arc(bloomX,bloomY,flower.size,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(255, 227, 155, 0.24)';ctx.beginPath();ctx.arc(bloomX,bloomY,flower.size*.42,0,Math.PI*2);ctx.fill()}}if(level>=4){for(const fly of ambientFireflies){const angle=time*fly.speed+fly.phase;const x=fly.x+Math.cos(angle)*fly.radius;const y=fly.y+Math.sin(angle*.8)*fly.radius*.38;const alpha=.22+Math.sin(time*.003+fly.phase)*.16;ctx.fillStyle=`rgba(255, 230, 150, ${Math.max(.06,alpha)})`;ctx.beginPath();ctx.arc(x,y,fly.size,0,Math.PI*2);ctx.fill()}}ctx.restore()}
function drawMistCatchers(time){const count=Math.min(reeds.length,3+state.upgrades.mist*2);ctx.save();ctx.lineCap='round';for(let i=0;i<count;i++){const reed=reeds[i];const sway=Math.sin(time*.001+reed.phase)*4;ctx.strokeStyle='rgba(135, 170, 138, .22)';ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(reed.x,reed.y);ctx.quadraticCurveTo(reed.x+sway,reed.y-reed.height*.55,reed.x+sway*1.4,reed.y-reed.height);ctx.stroke();ctx.fillStyle='rgba(190, 215, 180, .18)';ctx.beginPath();ctx.ellipse(reed.x+sway*1.5,reed.y-reed.height,4,9,sway*.03,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawMist(delta){for(const cloud of mist){cloud.x+=cloud.speed*delta*mistVisualBoost();if(cloud.x-cloud.radius>width){cloud.x=-cloud.radius;cloud.y=random(height*.58,height*.98)}const gradient=ctx.createRadialGradient(cloud.x,cloud.y,0,cloud.x,cloud.y,cloud.radius);gradient.addColorStop(0,`rgba(180, 210, 230, ${cloud.alpha*mistVisualBoost()})`);gradient.addColorStop(1,'rgba(180, 210, 230, 0)');ctx.fillStyle=gradient;ctx.beginPath();ctx.arc(cloud.x,cloud.y,cloud.radius,0,Math.PI*2);ctx.fill()}}
function drawDrops(delta){ctx.lineCap='round';for(let i=drops.length-1;i>=0;i--){const drop=drops[i];const previousY=drop.y,previousX=drop.x;drop.x+=drop.drift*delta;drop.y+=drop.speed*delta;if(previousY<drop.impactY&&drop.y>=drop.impactY){const t=(drop.impactY-previousY)/Math.max(drop.y-previousY,.001);const impactX=previousX+(drop.x-previousX)*t;addWater(waterPerDrop());createRipple(impactX,drop.impactY,.75+drop.depth*.7);drops.splice(i,1);continue}if(drop.y>height+80||drop.x<-160||drop.x>width+160){drops.splice(i,1);continue}const gradient=ctx.createLinearGradient(drop.x,drop.y-drop.length,drop.x+drop.drift*.04,drop.y);gradient.addColorStop(0,'rgba(205, 226, 242, 0)');gradient.addColorStop(.45,`rgba(205, 226, 242, ${drop.alpha})`);gradient.addColorStop(1,'rgba(205, 226, 242, 0)');ctx.strokeStyle=gradient;ctx.lineWidth=drop.lineWidth;ctx.beginPath();ctx.moveTo(drop.x,drop.y-drop.length);ctx.lineTo(drop.x+drop.drift*.055,drop.y);ctx.stroke()}}
function drawRipples(delta){for(let i=ripples.length-1;i>=0;i--){const ripple=ripples[i];ripple.radius+=ripple.growth*delta;ripple.alpha-=(ripple.warm?.07:.12)*delta;if(ripple.alpha<=0){ripples.splice(i,1);continue}ctx.strokeStyle=ripple.warm?`rgba(255, 219, 139, ${ripple.alpha})`:`rgba(185, 220, 240, ${ripple.alpha})`;ctx.lineWidth=ripple.warm?1.4:1+Math.min(.8,state.upgrades.ripples*.08);ctx.beginPath();ctx.ellipse(ripple.x,ripple.y,ripple.radius*ripple.stretch,ripple.radius*.45,0,0,Math.PI*2);ctx.stroke();if(ripple.double){ctx.strokeStyle=`rgba(185, 220, 240, ${ripple.alpha*.42})`;ctx.beginPath();ctx.ellipse(ripple.x,ripple.y,ripple.radius*ripple.stretch*1.34,ripple.radius*.58,0,0,Math.PI*2);ctx.stroke()}}}
function drawSpecial(delta){maybeStartSpecial(delta);if(!special)return;special.age+=delta;if(special.phase==='falling'){const previousY=special.y;special.x+=special.drift*delta;special.y+=special.speed*delta;const trail=ctx.createLinearGradient(special.x,special.y-special.length,special.x,special.y);trail.addColorStop(0,'rgba(255, 231, 158, 0)');trail.addColorStop(.55,'rgba(255, 231, 158, .9)');trail.addColorStop(1,'rgba(255, 255, 220, .1)');ctx.strokeStyle=trail;ctx.lineWidth=1.8;ctx.beginPath();ctx.moveTo(special.x,special.y-special.length);ctx.lineTo(special.x+special.drift*.08,special.y);ctx.stroke();if(previousY<special.impactY&&special.y>=special.impactY){addWater(waterPerDrop()*90);pulseHud();special.phase='bloom';special.age=0;special.y=special.impactY;for(let i=0;i<5;i++)createRipple(special.x,special.y,1.1+i*.34,true);sparks=Array.from({length:18+milestoneLevel()*3},()=>({x:special.x,y:special.y,vx:random(-24,24),vy:random(-52,-18),life:random(2.5,4.8),age:0,size:random(1.3,2.8)}))}return}const life=5.5,fade=Math.max(0,1-special.age/life),glowRadius=70+special.age*22;const glow=ctx.createRadialGradient(special.x,special.y,0,special.x,special.y,glowRadius);glow.addColorStop(0,`rgba(255, 224, 150, ${.22*fade})`);glow.addColorStop(1,'rgba(255, 224, 150, 0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(special.x,special.y,glowRadius,0,Math.PI*2);ctx.fill();for(let i=sparks.length-1;i>=0;i--){const spark=sparks[i];spark.age+=delta;spark.x+=spark.vx*delta;spark.y+=spark.vy*delta;spark.vy+=9*delta;const alpha=Math.max(0,1-spark.age/spark.life)*.75;ctx.fillStyle=`rgba(255, 230, 150, ${alpha})`;ctx.beginPath();ctx.arc(spark.x,spark.y,spark.size,0,Math.PI*2);ctx.fill();if(spark.age>=spark.life)sparks.splice(i,1)}if(special.age>=life){special=null;sparks=[]}}
function drawWindowGlow(time){const shimmer=.06+Math.sin(time*.0005)*.025;const glow=ctx.createLinearGradient(0,0,0,height);glow.addColorStop(0,`rgba(170, 205, 235, ${shimmer})`);glow.addColorStop(.5,'rgba(170, 205, 235, .015)');glow.addColorStop(1,'rgba(170, 205, 235, .03)');ctx.fillStyle=glow;ctx.fillRect(0,0,width,height)}
function handleDev(action){if(action==='water100')addWater(100);if(action==='water1000')addWater(1000);if(action==='nextMilestone'){const next=nextMilestone();if(next)addWater(Math.max(0,next.value-state.lifetimeWater))}if(action==='golden')forceGoldenDrop();if(action==='cloud')state.upgrades.clouds+=1;if(action==='ripple')state.upgrades.ripples+=1;if(action==='mist')state.upgrades.mist+=1;if(action==='reset')resetGame(true);trimActiveDrops();saveGame();updateUI();pulseHud();if(action!=='reset')showToast('Dev change applied.')}
function enableDevToolsIfRequested(){const params=new URLSearchParams(window.location.search);if(!params.has('dev')&&window.location.hash!=='#dev')return;ui.devToggle.classList.add('visible');showToast('Dev tools enabled.')}
let last=performance.now();
function animate(now){const delta=Math.min((now-last)/1000,.033);last=now;addWater(passivePerSecond()*delta);spawnDrops(delta);drawBackground(now);drawClouds(now);drawWindowGlow(now);drawMist(delta);drawGarden(now);drawDrops(delta);drawSpecial(delta);drawRipples(delta);updateUI(now);maybeAutoSave();requestAnimationFrame(animate)}
ui.buttons.forEach(button=>button.addEventListener('click',()=>buyUpgrade(button.dataset.upgrade)));
ui.panelButtons.forEach(button=>button.addEventListener('click',()=>setOpenPanel(button.dataset.panel)));
ui.closeButtons.forEach(button=>button.addEventListener('click',()=>closePanel(button.dataset.close)));
ui.devToggle.addEventListener('click',()=>ui.devPanel.classList.toggle('open'));
ui.devButtons.forEach(button=>button.addEventListener('click',()=>handleDev(button.dataset.dev)));
ui.reset.addEventListener('click',()=>resetGame());
window.addEventListener('resize',resize,{passive:true});
window.addEventListener('pagehide',saveGame);
document.addEventListener('visibilitychange',()=>{if(document.hidden)saveGame()});
loadGame();
seenMilestoneLevel=milestoneLevel();
resize();
updateUI();
enableDevToolsIfRequested();
saveGame();
requestAnimationFrame(animate);
